### PR TITLE
UI enhancement

### PR DESCRIPTION
**Pull request by huzaifaazim0**
Screenshot 2024-02-22 at 5 11 46 PM

changed files :

1- index.html
2- style.css
3- main.js

### CODE REVIEW

**Comment by ShadBalti** [comment]
you also remove metadata and footer session.
Please check your changing

**Comment by huzaifaazim0** [comment]
Hello
Sure I will check again

Thanks

**Comment by huzaifaazim0** [comment]
added meta tags
and footer was already there

**Comment by ShadBalti** [comment]
Thanks for contributing

**Comment by huzaifaazim0** [comment]
no prob
anytime

**Pull request merged**
